### ISSUE TITLE
Sorting the auditlog fails with #9875

### ISSUE THREAD

**Issue by phavekes** [OpenConext/Stepup-RA#365]
[This issue is imported from pivotal - Originaly created at Oct 27, 2016 by Pieter van der Meulen](https://www.pivotaltracker.com/story/show/133246727)

Sorting the audit log fails with error #9875 (release 7)

Reproduce:
* In the RA go to "Tokens"
* Select "Audit log" of a token
* Click on  "Token Identifier"
Sorting fails for the columns: "Token Identifier", "Event" and "By". Sorting on "Token type" and "Date" works as expected.

**Comment by phavekes** [comment]
It seems to me something goes wrong in Middleware translating the query coming from RA. Debugging should start in Middleware\'s AuditLogService and AuditLogRepository to make sure the correct (Doctrine) fields are being referred to when ordering.

The logs show the following:

* Token-identifier: `Unknown order by column "secondFactorIdentifier"`
* Event: `Unknown order by column "action"`
* By: `Unknown order by column "actorCommonName"`

The stack traces for the latter are:

Middleware:
```
Surfnet\StepupMiddleware\ApiBundle\Exception\RuntimeException: "Unknown order by column "actorCommonName""

#0 /var/www/mw-dev.stepup.coin.surf.net/src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/AuditLogService.php(43): Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\AuditLogRepository->createSecondFactorSearchQuery(Object(Surfnet\StepupMiddleware\ApiBundle\Identity\Query\SecondFactorAuditLogQuery))
#1 /var/www/mw-dev.stepup.coin.surf.net/src/Surfnet/StepupMiddleware/ApiBundle/Controller/AuditLogController.php(47): Surfnet\StepupMiddleware\ApiBundle\Identity\Service\AuditLogService->searchSecondFactorAuditLog(Object(Surfnet\StepupMiddleware\ApiBundle\Identity\Query\SecondFactorAuditLogQuery))
#2 [internal function]: Surfnet\StepupMiddleware\ApiBundle\Controller\AuditLogController->secondFactorAuditLogAction(Object(Symfony\Component\HttpFoundation\Request), Object(Surfnet\Stepup\Identity\Value\Institution))
#3 /var/www/mw-dev.stepup.coin.surf.net/app/bootstrap.php.cache(3156): call_user_func_array(Array, Array)
#4 /var/www/mw-dev.stepup.coin.surf.net/app/bootstrap.php.cache(3115): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/mw-dev.stepup.coin.surf.net/app/bootstrap.php.cache(3269): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/mw-dev.stepup.coin.surf.net/app/bootstrap.php.cache(2480): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/mw-dev.stepup.coin.surf.net/web/app_dev.php(15): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
```

RA:
```
Surfnet\StepupMiddlewareClient\Exception\ResourceReadException: "Resource could not be read (status code 500)"

#0 /var/www/ra-dev.stepup.coin.surf.net/vendor/surfnet/stepup-middleware-client-bundle/src/Surfnet/StepupMiddlewareClient/Identity/Service/AuditLogService.php(54): Surfnet\StepupMiddlewareClient\Service\ApiService->read(\'audit-log/secon...\')
#1 /var/www/ra-dev.stepup.coin.surf.net/vendor/surfnet/stepup-middleware-client-bundle/src/Surfnet/StepupMiddlewareClientBundle/Identity/Service/AuditLogService.php(62): Surfnet\StepupMiddlewareClient\Identity\Service\AuditLogService->searchSecondFactorAuditLog(Object(Surfnet\StepupMiddlewareClient\Identity\Dto\SecondFactorAuditLogSearchQuery))
#2 /var/www/ra-dev.stepup.coin.surf.net/src/Surfnet/StepupRa/RaBundle/Service/AuditLogService.php(48): Surfnet\StepupMiddlewareClientBundle\Identity\Service\AuditLogService->searchSecondFactorAuditLog(Object(Surfnet\StepupMiddlewareClient\Identity\Dto\SecondFactorAuditLogSearchQuery))
#3 /var/www/ra-dev.stepup.coin.surf.net/src/Surfnet/StepupRa/RaBundle/Controller/SecondFactorController.php(164): Surfnet\StepupRa\RaBundle\Service\AuditLogService->getAuditlog(Object(Surfnet\StepupRa\RaBundle\Command\SearchSecondFactorAuditLogCommand))
#4 [internal function]: Surfnet\StepupRa\RaBundle\Controller\SecondFactorController->auditLogAction(Object(Symfony\Component\HttpFoundation\Request))
#5 /var/www/ra-dev.stepup.coin.surf.net/app/bootstrap.php.cache(3133): call_user_func_array(Array, Array)
#6 /var/www/ra-dev.stepup.coin.surf.net/app/bootstrap.php.cache(3095): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /var/www/ra-dev.stepup.coin.surf.net/app/bootstrap.php.cache(3246): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /var/www/ra-dev.stepup.coin.surf.net/app/bootstrap.php.cache(2462): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/ra-dev.stepup.coin.surf.net/web/app_dev.php(15): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#10 {main}
```
 (Alex Rothuis - Oct 31, 2016)
